@extends('admin.layout')
@section('title', $vendor->exists ? 'Edit vendor' : 'Add vendor')
@section('content')
<div class="heading"><div><a href="{{ route('admin.vendors.index') }}">← All vendors</a><h1>{{ $vendor->exists ? $vendor->business_name : 'Add vendor' }}</h1></div>@if($vendor->exists)<form method="POST" action="{{ route('admin.vendors.sync-pickup', $vendor) }}">@csrf<button class="button">Sync Shiprocket pickup</button></form>@endif</div>
<form class="panel" method="POST" action="{{ $vendor->exists ? route('admin.vendors.update', $vendor) : route('admin.vendors.store') }}">@csrf @if($vendor->exists)@method('PUT')@endif
<h2>Business details</h2><div class="form-grid"><label>Business name<input name="business_name" required maxlength="150" value="{{ old('business_name', $vendor->business_name) }}"></label><label>Contact person<input name="contact_person" required maxlength="120" value="{{ old('contact_person', $vendor->contact_person) }}"></label><label>Email<input name="email" type="email" required maxlength="150" value="{{ old('email', $vendor->email) }}"></label><label>Phone<input name="phone" required maxlength="20" value="{{ old('phone', $vendor->phone) }}"></label><label>Status<select name="is_active"><option value="1" @selected((string) old('is_active', (int) $vendor->is_active) === '1')>Active</option><option value="0" @selected((string) old('is_active', (int) $vendor->is_active) === '0')>Inactive</option></select></label></div>
<h2>Pickup address</h2><div class="form-grid"><label class="wide">Address<input name="pickup_address" required maxlength="500" value="{{ old('pickup_address', $vendor->pickup_address) }}"></label><label class="wide">Address 2<input name="pickup_address_2" maxlength="500" value="{{ old('pickup_address_2', $vendor->pickup_address_2) }}"></label><label>City<input name="pickup_city" required maxlength="80" value="{{ old('pickup_city', $vendor->pickup_city) }}"></label><label>State<input name="pickup_state" required maxlength="80" value="{{ old('pickup_state', $vendor->pickup_state) }}"></label><label>Postal code<input name="pickup_postal_code" required maxlength="12" value="{{ old('pickup_postal_code', $vendor->pickup_postal_code) }}"></label><label>Country<input name="pickup_country" required maxlength="80" value="{{ old('pickup_country', $vendor->pickup_country ?: 'India') }}"></label><label class="wide">Return address<textarea name="return_address" rows="3" maxlength="800">{{ old('return_address', $vendor->return_address) }}</textarea></label><label class="wide">Pickup instructions<textarea name="pickup_instructions" rows="3" maxlength="800">{{ old('pickup_instructions', $vendor->pickup_instructions) }}</textarea></label><label>Shiprocket pickup code<input name="shiprocket_pickup_location" maxlength="120" value="{{ old('shiprocket_pickup_location', $vendor->shiprocket_pickup_location) }}"><small>Leave blank until synced, or enter an existing Shiprocket pickup location code.</small></label></div>
<h2>Vendor portal user</h2><div class="form-grid"><label>Name<input name="portal_name" maxlength="120" value="{{ old('portal_name', $vendor->users->first()?->name) }}"></label><label>Email<input name="portal_email" type="email" maxlength="150" value="{{ old('portal_email', $vendor->users->first()?->email) }}"></label><label>Password<input name="portal_password" type="password" minlength="12" autocomplete="new-password"><small>Set only when creating or rotating access.</small></label></div>
<button class="button">{{ $vendor->exists ? 'Save vendor' : 'Create vendor' }}</button>
</form>
@endsection
